// <auto-generated />
namespace Vidly2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class no_require_movie_genre_in_movie_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(no_require_movie_genre_in_movie_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202305221626351_no_require_movie_genre_in_movie_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
